### ISSUE TITLE
Memory heap getting bigger

### ISSUE THREAD

**Issue by amirshams84** [vtsyvina/CliqueSNV#4]
Hi,
I am running the clique svn over a bam file from HIV virus about 140MB

`java -Xms50000M -Xmx50000M -jar /clique-snv.jar -m snv-illumina -in TestHIV.trimmed_fastp.mapped_bowtie2.bam -threads 30 -outDir $TEMP_PATH`
the bam is already cleaned 
the memory expansion is getting larger and larger
-loop1 20GB failed
-loop2 30GB failed
-loop3 50 GB failed
-loop4 100GB still going

is there any way that we can decrease the amount of memory requirement?
Ideas1> removing duplicates from BAM
Ideas 2> splitting bam

how can I estimate the amount of memory required?
something like: the number of reads * number of core + cosmos diameter / IO speed

Thanks

**Comment by amirshams84** [comment]
Hi,
Thanks for the quick reply
here is the log file generated and it reached 91.2GB so I think is it going fail again
[HIVtest.trimmed_fastp.mapped_bowtie2.haplotype_cliquesnv.log](https://github.com/vtsyvina/CliqueSNV/files/5002672/HIVtest.trimmed_fastp.mapped_bowtie2.haplotype_cliquesnv.log)

**Comment by amirshams84** [comment]
Hi,
Thanks for the quick reply
here is the log file generated and it reached 91.2GB so I think is it going fail again
[HIVtest.trimmed_fastp.mapped_bowtie2.haplotype_cliquesnv.log](https://github.com/vtsyvina/CliqueSNV/files/5002687/HIVtest.trimmed_fastp.mapped_bowtie2.haplotype_cliquesnv.log)

**Comment by vtsyvina** [comment]
It is strange. And what is the stack trace when it runs out of memory? So I can see at what exact place it fails

**Comment by amirshams84** [comment]
I am not sure how to get the stack trace, but I can hand you over the bam file if you want to try
let me know which method works for you

**Comment by vtsyvina** [comment]
Yes, with bam file it will be even easier to find the problem. 
Thanks

P.S. Stack trace is just the error with which it fails. Something like this:
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.HashMap.newNode(HashMap.java:1742)
        at java.util.HashMap.putVal(HashMap.java:630)
        at java.util.HashMap.put(HashMap.java:611)
        at java.util.HashSet.add(HashSet.java:219)
        at edu.gsu.algorithm.AbstractSNV.slowCliquesMerging(AbstractSNV.java:401)
        at edu.gsu.algorithm.AbstractSNV.getMergedCliques(AbstractSNV.java:59)
        at edu.gsu.algorithm.SNVIlluminaMethod.getMergedCliques(SNVIlluminaMethod.java:213)
        at edu.gsu.algorithm.SNVIlluminaMethod.getHaplotypes(SNVIlluminaMethod.java:103)
        at edu.gsu.start.Start.illumina2SNV(Start.java:108)
        at edu.gsu.start.Start.main(Start.java:56)

**Comment by amirshams84** [comment]
it seems the problem was with the bam file not the application
